### ISSUE TITLE
Tasks for Completion

### ISSUE THREAD

**Issue by leggant** [leggant/Batch-Script-Assignment-2020#3]
- [x] **A1:** Output a line to the screen that displays your name

- [x] **A2:** Create a folder on the root of the C: drive called “My Batch Script File Assignment”

- [x] **A3:** Change into the “My Batch Script File Assignment” folder.

- [x] **A4:** Create a folder within “My Batch Script File Assignment” called “Input”

- [x] **A5:** Create another folder within “My Batch Script File Assignment” called “Processing”

- [x] **A6:** Create another folder within “My Batch Script File Assignment” called “Output”

- [x] **A7:** List all hidden files in the root directory of the C: drive – output the listing to a file called “Input Data.txt” in the “Input” subfolder.
(In this assignment, you won’t be using the contents of this file as actual input, but it is possible to do so.)

- [x] **A8:** Make a backup copy of Input Data.txt on the root of the C: drive, and with the same name, but with extension “.bak”.

- [x] **A9:** Go to the root directory of the C: drive
(This command must work the same from whichever drive, folder or subfolder the script is currently in.)

- [x] **A10:** Update the folder search path for batch script file execution to include the “Processing” subfolder, and then display the folder search path.
(Make sure you preserve the folders that were already in the search path.)

- [x] **A11:** Change the command prompt to include the time, the words “Hello World” and the ‘>’ character (to demonstrate this on the screen, you might need to temporarily alter the setting so that the lines from the batch script file are displayed to the screen as they are processed.)

- [x] **A12:** Create a new command window, with red coloured text and green background (to do this, you will need two commands on the same line; one is CMD – type ‘CMD /?’ for help; the other command is in the HELP list.)

- [x] **A13:** Create another new command window, with blue coloured text and a bright white background, and with a prompt that includes the Windows version number.

- [x] **A14:** List all the folders (not files) in C:\WINDOWS\System32, (or 64-bit equivalent) sorted into alphabetical order – output the listing to a file called “Batch Script File Output Data.txt” in the “Output” subfolder.
 
- [x] **A15:** List all text files whose names are up to seven characters long on the whole C: drive – make the listing output in wide format – the listing output must be appended to the end of “Batch Script File Output Data.txt”

- [ ] **A16:** Delete folder “My Batch Script File Assignment”, together with all subfolders and their contents.

- [ ] **A17:** Output to the screen the configuration information relating to your network settings.

- [ ] **A18:** Create a local user called “Bob”, then create a local group called “Awesome Users” and add Bob to it.

- [ ] **A19:** Delete the group “Awesome Users” and delete the user “Bob”.

- [ ] **A20:** Create a task to be scheduled at 10 pm every Sunday that will check the C disk for errors and write the results to a file called “chkdskResults.txt” on the desktop.

**Comment by leggant** [comment]
## Tasks > A15 Now Completed and Tested

**Now Working on Final 5 Questions.
